name: Main

on: 
  push:
    branches: [ "main" ]
    tags:
      - "v*.*"
  
  workflow_dispatch:

permissions:
  contents: write      

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: |
          mkdir release
          cp *.exe ./release
          echo ${{ github.sha }} > ./release/Release.txt

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./release/*
            
