name: Main

on: 
  push:
    tags:
      - "v*.*"
  
  workflow_dispatch:

permissions:
  contents: read,write      

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: |
          mkdir release
          cp *.exe ./release
          echo ${{ github.sha }} > ./release/Release.txt

      - name: Archive Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: "G14 Helper"
          path: release/*

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./release/*
            artifacts/*
            
